### ISSUE TITLE
Keep Track of # songs played in event in Base Class

### ISSUE THREAD

**Issue by abuneri** [Injabie3/LLSIF-Helper#11]
will help with the calculation of average score if we have a way to let the user increment number of songs played, also is just good data to have across all events

**Comment by Injabie3** [comment]
You mean just straight up the number of songs played? We need a hard definition of what you want that to represent, like:
- Number of songs (event song? regular song?)
- Number of songs (based on the difficulty selected)

**Comment by abuneri** [comment]
sorry for late response @Injabie3 somehow i missed seeing this. i would just need the number of songs the person has played related to the event song. cuz i need to keep calculating average score, so would be easy if i could access a variable that was already been tracked in base class and just use that to divide by the sum of the score

EDIT:
 it wont be exact because of token collection, but the simple fix for that would be to just add on the amount of tokens they had in total and divide it by one of the max LP's (eg 27 for expert song) and it would give a pretty close approximation. this is all of course in addition to keeping track of the amount of times they play actual event songs (easier to implement for scorematch).

does this kinda make sense?

**Comment by abuneri** [comment]
i also just remembered that average score is only needed for sccore match (not sure about medley festival but we'll cross that bridge later) so it simply just needs to be the number of songs they do in score match

**Comment by Injabie3** [comment]
So number of songs played overall in the event? Sounds good.

**Comment by Injabie3** [comment]
Implemented in 28da7f706a5108ecc090b6dc9f10bc379385baf0
