### ISSUE TITLE
rankUp Class

### ISSUE THREAD

**Issue by Injabie3** [Injabie3/LLSIF-Helper#6]
Create a class that contains the following: 
Variables for:
- Current XP
- Total XP for current rank.
  Calculate:
- LP required to reach next rank (for all difficulties), and store that in their own class variables.

**Comment by Injabie3** [comment]
Implementing this via a base class (LLSIFBase) and deriving based on events, as seen in commit d73290b369be91a7b448b1d988f69fa17529b0cd.

**Comment by abuneri** [comment]
should this issue be closed since it was merged into the base class?

**Comment by Injabie3** [comment]
True that.
