### ISSUE TITLE
Custom UI

### ISSUE THREAD

**Issue by Injabie3** [Injabie3/LLSIF-Helper#7]
We have to move away from Windows Forms. Having so many problems with compatibility on different screens. On one computer, it's fine; on another, labels are shifted and nothing is aligned properly.

**Comment by abuneri** [comment]
I wonder if we could also look into the options of making this a straightup desktop app as well and just make our own custom GUI from a template we could find online (No windows forms please, oh god). That way we could keep our c++ and actually use it, then the Java side of things could continue as well with Android Studio. 

Proposed GUI library: http://www.fox-toolkit.org/

**Comment by Injabie3** [comment]
That would be ideal, yes.

On Sat, Apr 9, 2016, 12:14 Ashton Tito notifications@github.com wrote:

> I wonder if we could also look into the options of making this a
> straightup desktop app as well and just make our own custom GUI from a
> template we could find online (No windows forms please, oh god). That way
> we could keep our c++ and actually use it, then the Java side of things
> could continue as well with Android Studio.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Injabie3/LLSIF-Helper/issues/7#issuecomment-207836251
> 
> ## 

Ryan Lui
Sent via Sony Xperia M4 Aqua

**Comment by abuneri** [comment]
no plans to do android app for now
